parameters:
    da_api_client.api.class:                      Da\ApiClientBundle\Http\ApiClient\RestApiClientBridge
    da_api_client.api_implementor.class:          Da\ApiClientBundle\Http\ApiClient\RestApiClientBasicImplementor
    da_api_client.rest_logger.class:              Da\ApiClientBundle\Http\Logger\DebugStack
    da_api_client.data_collector.class:           Da\ApiClientBundle\DataCollector\RestApiClientDataCollector

services:
    da_api_client.api:
        class:     %da_api_client.api.class%
        arguments: [null, null]
        abstract:  true

    da_api_client.api_implementor:
        class:     %da_api_client.api_implementor.class%
        arguments: [@service_container]
        abstract:  true
        public:    false

    da_api_client.rest_logger:
        class:     %da_api_client.rest_logger.class%
        public:    false

    da_api_client.data_collector:
        class:     %da_api_client.data_collector.class%
        arguments: [@da_api_client.rest_logger]
        public:    false
        tags:
            - { name: data_collector, template: 'DaApiClientBundle:Collector:rest', id: rest_api }
