parameters:
    da_api_client.api.class:                      Da\ApiClientBundle\Http\Rest\RestApiClientBridge
    da_api_client.api_implementor.class:          Da\ApiClientBundle\Http\Rest\RestApiClientBasicImplementor
    da_api_client.http_logger.class:              Da\ApiClientBundle\Logger\HttpDebugStack
    da_api_client.data_collector.class:           Da\ApiClientBundle\DataCollector\ApiClientDataCollector

services:
    da_api_client.api:
        class:     %da_api_client.api.class%
        arguments: [null, null]
        abstract:  true

    da_api_client.api_implementor:
        class:     %da_api_client.api_implementor.class%
        arguments: [@service_container]
        abstract:  true
        public:    false

    da_api_client.http_logger:
        class:     %da_api_client.http_logger.class%
        arguments: [@service_container]
        public:    false

    da_api_client.data_collector:
        class:     %da_api_client.data_collector.class%
        arguments: [@da_api_client.http_logger]
        public:    false
        tags:
            - { name: data_collector, template: 'DaApiClientBundle:Collector:api', id: api }
